### ISSUE TITLE
Vertaisarviointi

### ISSUE THREAD

**Issue by pllk** [jt551/bicyclemarketplace#1]
Käyttökokemus:

* Pystyin luomaan tunnuksen ja kirjautumaan sisään. Koetin myös lähettää viestin, mutta en ole varma, mitä siinä tapahtui.

* Sovelluksen ulkoasu on jo nyt todella tyylikäs.

* Lomakkeissa ei näytä hyvältä, että tekstikentät ulottuvat sivun reunasta reunaan.

Tekniset asiat:

* Koodi on hyvin muotoiltu ja selkeää.

* Pitkät SQL-komennot voisi olla hyvä jakaa usealle riville koodissa.

* Tiedostossa `routes.py` rivillä 37 on ehkä unohtunut debug-tulostus.

* Tiedostossa `users.py` rivien 22-25 koodin voisi kirjoittaa lyhemmin näin:

```python
    return user.id if user else 0
```

**Comment by jt551** [comment]
Kiitos arviosta. 
Parannusehdotukset työjonossa.
